<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <style>
        body { font-family: DejaVu Sans, sans-serif; font-size: 11px; color: #1e293b; }
        .header { text-align: center; margin-bottom: 24px; padding-bottom: 16px; border-bottom: 2px solid #059669; }
        .header h1 { color: #059669; font-size: 20px; margin: 0 0 4px; }
        .header p { color: #64748b; font-size: 11px; margin: 2px 0; }
        .info-table { width: 100%; margin-bottom: 20px; }
        .info-table td { padding: 3px 8px; vertical-align: top; }
        .info-table td:first-child { width: 140px; color: #64748b; }
        .info-table td:last-child { font-weight: 500; }
        table.items { width: 100%; border-collapse: collapse; margin: 16px 0; }
        table.items th { background: #059669; color: white; padding: 8px; text-align: left; font-size: 10px; text-transform: uppercase; }
        table.items td { padding: 8px; border-bottom: 1px solid #e2e8f0; }
        table.items tr:last-child td { border-bottom: none; }
        .totals { width: 300px; margin-left: auto; }
        .totals td { padding: 4px 8px; }
        .totals .grand-total { font-size: 14px; font-weight: bold; color: #059669; border-top: 2px solid #059669; }
        .notes { margin-top: 24px; padding: 12px; background: #f8fafc; border-radius: 4px; color: #64748b; font-size: 10px; }
        .footer { margin-top: 32px; padding-top: 12px; border-top: 1px solid #e2e8f0; text-align: center; color: #94a3b8; font-size: 9px; }
    </style>
</head>
<body>
    <div class="header">
        <h1>{{ $invoice->type === 'credit_note' ? 'CREDIT NOTE' : ($invoice->type === 'debit_note' ? 'DEBIT NOTE' : 'INVOICE') }}</h1>
        <p>{{ $invoice->reference }}</p>
    </div>

    <table class="info-table">
        <tr><td>Client</td><td>{{ $invoice->client->name }}</td></tr>
        @if($invoice->client->address)<tr><td>Address</td><td>{{ $invoice->client->address }}</td></tr>@endif
        <tr><td>Issue Date</td><td>{{ $invoice->issue_date->format('M d, Y') }}</td></tr>
        <tr><td>Due Date</td><td>{{ $invoice->due_date->format('M d, Y') }}</td></tr>
        <tr><td>Status</td><td>{{ ucfirst($invoice->status) }}</td></tr>
        @if($invoice->order)<tr><td>Order</td><td>{{ $invoice->order->reference }}</td></tr>@endif
        @if($invoice->contract)<tr><td>Contract</td><td>{{ $invoice->contract->reference }}</td></tr>@endif
    </table>

    <table class="items">
        <thead>
            <tr>
                <th style="width:50%">Description</th>
                <th style="width:80px">Qty</th>
                <th style="width:100px">Unit Price</th>
                <th style="width:100px; text-align:right">Total</th>
            </tr>
        </thead>
        <tbody>
            @foreach($invoice->items as $item)
            <tr>
                <td>{{ $item->description }}</td>
                <td>{{ number_format($item->quantity, 2) }}</td>
                <td>{{ number_format($item->unit_price, 2) }} {{ $invoice->currency->code }}</td>
                <td style="text-align:right">{{ number_format($item->total, 2) }} {{ $invoice->currency->code }}</td>
            </tr>
            @endforeach
        </tbody>
    </table>

    <table class="totals">
        <tr><td>Subtotal</td><td style="text-align:right">{{ number_format($invoice->subtotal, 2) }} {{ $invoice->currency->code }}</td></tr>
        @if($invoice->discount_total > 0)
        <tr><td>Discount</td><td style="text-align:right; color:#dc2626;">-{{ number_format($invoice->discount_total, 2) }} {{ $invoice->currency->code }}</td></tr>
        @endif
        <tr><td>Tax (18%)</td><td style="text-align:right">{{ number_format($invoice->tax_total, 2) }} {{ $invoice->currency->code }}</td></tr>
        <tr class="grand-total"><td>TOTAL</td><td style="text-align:right">{{ number_format($invoice->total, 2) }} {{ $invoice->currency->code }}</td></tr>
    </table>

    @if($invoice->notes)
    <div class="notes">
        <strong>Notes:</strong><br>{{ $invoice->notes }}
    </div>
    @endif

    <div class="footer">
        Generated by Martin Logistics System on {{ now()->format('M d, Y H:i') }}
    </div>
</body>
</html>
